import React from "react";
import "@/app/global.css";
import { TicketProvider } from "../app/TicketContext"; 

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <TicketProvider>
          <div id="container">
            <div id="main">{children}</div>
          </div>
          {/* Company Contact Info Section */}
          <footer className="bg-cyan-400">
            <h2>Contact Information</h2>
            <p>Company Name: Your Company Name</p>
            <p>CVR: 12345678</p>
            <p>Address: 1234 Business St., City, Country</p>
            <p>Email: info@yourcompany.com</p>
            <p>Phone: +1 234 567 8900</p>
          </footer>
        </TicketProvider>
      </body>
    </html>
  );
}
